name: "live-editor"
services:
  api:
    build:
      context: './api'
      dockerfile: 'deploy.dockerfile'
    restart: "unless-stopped"
    working_dir: /api
    environment:
      API: "https://api.live-editor.ikeoha.xyz"
    ports:
      - "8000:8000"


  web:
    build:
      context: './web'
      dockerfile: 'deploy.dockerfile'
    restart: "unless-stopped"
    working_dir: /web
    environment:
      VITE_API: https://api.live-editor.ikeoha.xyz
    ports:
      - "8001:8001"

  server:
    image: "caddy:alpine"
    restart: "unless-stopped"
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - editor_caddy_data:/data
      - editor_caddy_config:/config
    
volumes:
  editor_caddy_data:
    external: true
  editor_caddy_config:
