name: "live-editor"
services:
  api:
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/api

  web:
    image: "node:alpine"
    command: sh -c "npm ci && npm run dev"
    working_dir: /web
    environment:
      VITE_API: "http://localhost:8000"
    ports:
      - 8001:5173
    volumes:
      - ./web:/web
