FROM node:20.11.1-alpine

ENV GO_VERSION 1.22.1

RUN apk update && \
    apk add --no-cache \
    curl \
    wget

RUN npm install -g sass \
    && npm install -g typescript

# install go
RUN wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz

ENV PATH /usr/local/go/bin:$PATH

EXPOSE 8000
WORKDIR /api
CMD ["go", "run", "main.go"]